### ISSUE TITLE
error on install

### ISSUE THREAD

**Issue by gras64** [andlo/theia-ide-skill#1]
Traceback (most recent call last):
      File "/tmp/pip-install-6j3ipsen/pyls/setup_utils/distribute_setup.py", line 143, in use_setuptools
        raise ImportError
    ImportError
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-6j3ipsen/pyls/setup.py", line 31, in <module>
        main()
      File "/tmp/pip-install-6j3ipsen/pyls/setup.py", line 11, in main
        distribute_setup.use_setuptools()
      File "/tmp/pip-install-6j3ipsen/pyls/setup_utils/distribute_setup.py", line 145, in use_setuptools
        return _do_download(version, download_base, to_dir, download_delay)
      File "/tmp/pip-install-6j3ipsen/pyls/setup_utils/distribute_setup.py", line 124, in _do_download
        to_dir, download_delay)
      File "/tmp/pip-install-6j3ipsen/pyls/setup_utils/distribute_setup.py", line 193, in download_setuptools
        src = urlopen(url)
      File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
        return opener.open(url, data, timeout)
      File "/usr/lib/python3.5/urllib/request.py", line 472, in open
        response = meth(req, response)
      File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
        'http', request, response, code, msg, hdrs)
      File "/usr/lib/python3.5/urllib/request.py", line 510, in error
        return self._call_chain(*args)
      File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
        result = func(*args)
      File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
        raise HTTPError(req.full_url, code, msg, hdrs, fp)
    urllib.error.HTTPError: HTTP Error 403: SSL is required

**Comment by andlo** [comment]
I saw that. I changed the requerements.txt and removed pyls, as it seems like that did the problems,

I have now done a clean install of picroft and installed the skill to make sure it did correct.
